// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB3ZTu-WIhvxF1qtjU5Lp9GOTpYjmPEMA',
    appId: '1:649783742740:web:45336fb989dcf1f6743201',
    messagingSenderId: '649783742740',
    projectId: 'sisoil-9cb24',
    authDomain: 'sisoil-9cb24.firebaseapp.com',
    databaseURL: 'https://sisoil-9cb24-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sisoil-9cb24.appspot.com',
    measurementId: 'G-2YKTM4VEQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzAJFHAQ2zs_JVFnviGnqMvOFWiLENwaU',
    appId: '1:649783742740:android:c5fb27e0c5c331fe743201',
    messagingSenderId: '649783742740',
    projectId: 'sisoil-9cb24',
    databaseURL: 'https://sisoil-9cb24-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sisoil-9cb24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI6f8c-1sio3E_pnwcQcYXOHE-kLIS-EQ',
    appId: '1:649783742740:ios:a204de21af115065743201',
    messagingSenderId: '649783742740',
    projectId: 'sisoil-9cb24',
    databaseURL: 'https://sisoil-9cb24-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sisoil-9cb24.appspot.com',
    iosClientId: '649783742740-f100bbj3195ncsdk4lm2m5t3g69s8pel.apps.googleusercontent.com',
    iosBundleId: 'com.example.newAgrisoilApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI6f8c-1sio3E_pnwcQcYXOHE-kLIS-EQ',
    appId: '1:649783742740:ios:a204de21af115065743201',
    messagingSenderId: '649783742740',
    projectId: 'sisoil-9cb24',
    databaseURL: 'https://sisoil-9cb24-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sisoil-9cb24.appspot.com',
    iosClientId: '649783742740-f100bbj3195ncsdk4lm2m5t3g69s8pel.apps.googleusercontent.com',
    iosBundleId: 'com.example.newAgrisoilApp',
  );
}
